spring:
 application:
  name: purchases

 # JPA
 datasource:
  url: jdbc:h2:mem:shopping_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  driver-class-name: org.h2.Driver
  username: sa
  password: ""

 jpa:
   hibernate:
    ddl-auto: none #  create -> Generar las tablas a partir de las entidades
   properties:
    hibernate:
     dialect: org.hibernate.dialect.H2Dialect
   defer-datasource-initialization: true

 sql:
  init:
   mode: always
   platform: h2


 data:
  redis:
   host: localhost
   port: 6379

 h2:
  console:
   enabled: true
   path: /h2-console

logging:
 pattern:
  console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n"

server:
 servlet:
  context-path: /api/v1


